SHEET_ID = "1FcqyIV1i7ARd4DRAtD2mCIiS3orSrUpA9wORUyGbCMA"

TS_SCHEDULE_RANGE = "TS_Schedule!A2:Z"
SSSL_SCHEDULE_RANGE = "SSSL_Schedule!A2:Z"
MAPPING_RANGE = "TS_SSSL_Mapping!A2:G"
COMPARISON_RANGE = "Score_Comparison!A2:Z"
